# Configuration file for the latent model analysis

# File paths
# Note: Please update these paths to point to your data and results directories.
data_dir <- "data/"
results_dir <- "results/"

ground_truth_file <- paste0(data_dir, "cvdgt.txt")
# The following files are generated by latentModel.R and used by tables_figures.R
# The paths are constructed in the scripts themselves, but the base names are defined here.
gt_sample_prefix <- "g"
syn_sample_prefix <- "s"
klds_file <- paste0(results_dir, "KLDS.txt")

# Model parameters
sample_size <- 122328
num_bootstrap_samples <- 10
num_latent_vars <- 6
num_latent_states <- c(2, 3, 4)
num_iterations <- 10
