# Demonstration script for the latent model analysis
#
# This script demonstrates a use case of the synthetic data generated by latentModel.R.
# It loads the ground truth data, generates a synthetic sample on the fly,
# trains a predictive model on the synthetic data, and evaluates it on the ground truth data.

# Load libraries
library(dplyr)
library(summarytools)
library(caret)

# Load configuration and the generator function
source("scripts/config.R")
source("scripts/latentModel.R")

# -----------------------------------------------------------------------------
# Generate Data for Demonstration
# -----------------------------------------------------------------------------

cat("\n--- Loading Ground Truth Data and Generating Synthetic Data ---\n")

# Load the full ground truth data
ground_truth_data <- read.delim(ground_truth_file)

# Take a sample for the demonstration
# Using a smaller sample size for a quicker demonstration
set.seed(42)
gt_sample <- ground_truth_data[sample(nrow(ground_truth_data), 10000), ]

# Generate synthetic data on the fly by calling the function
# This can take some time depending on the sample size
syn_sample <- generate_synthetic_data(gt_sample)

cat("Synthetic data generated successfully.\n")


# -----------------------------------------------------------------------------
# Compare Data
# -----------------------------------------------------------------------------

cat("\n--- Data Summary Comparison ---\n\n")

cat("Ground Truth Data Summary:\n")
print(dfSummary(gt_sample), method = "render")

cat("\nSynthetic Data Summary:\n")
print(dfSummary(syn_sample), method = "render")


# -----------------------------------------------------------------------------
# Train a Predictive Model
# -----------------------------------------------------------------------------

cat("\n--- Training a Predictive Model on Synthetic Data ---\n\n")

# We will train a logistic regression model to predict 'strokeha'

# The outcome variable needs to be a factor with valid level names for caret
syn_sample$strokeha <- as.factor(syn_sample$strokeha)
gt_sample$strokeha <- as.factor(gt_sample$strokeha)
levels(syn_sample$strokeha) <- make.names(levels(syn_sample$strokeha))
levels(gt_sample$strokeha) <- make.names(levels(gt_sample$strokeha))


# Define the model formula
# Using a subset of variables for demonstration purposes
formula <- strokeha ~ age + bmi + gender + choleratio + sbp

# Train the logistic regression model on the synthetic data
set.seed(123) # for reproducibility
model <- train(
  formula,
  data = syn_sample,
  method = "glm",
  family = "binomial",
  trControl = trainControl(method = "none") # No resampling for this demo
)

cat("Model trained on synthetic data:\n")
print(summary(model))


# -----------------------------------------------------------------------------
# Evaluate the Model on Ground Truth Data
# -----------------------------------------------------------------------------

cat("\n--- Evaluating the Model on Ground Truth Data ---\n\n")

# Make predictions on the ground truth data
predictions <- predict(model, newdata = gt_sample)

# Create a confusion matrix
confusion_matrix <- confusionMatrix(predictions, gt_sample$strokeha)

cat("Confusion Matrix and Statistics:\n")
print(confusion_matrix)

cat("\n--- Demonstration Complete ---\n")
