# Demonstration script for the latent model analysis
#
# This script demonstrates a use case of the synthetic data generated by latentModel.R.
# It loads a ground truth sample and a synthetic sample, trains a predictive model on the
# synthetic data, and evaluates it on the ground truth data.

# Load libraries
library(dplyr)
library(summarytools)
library(caret)

# Load configuration
source("scripts/config.R")

# The rest of the script will be added in the next steps.


# -----------------------------------------------------------------------------
# Load and Compare Data
# -----------------------------------------------------------------------------

# Choose which iteration to use for the demonstration
# This assumes that latentModel.R has been run and has produced at least one set of samples.
iteration_to_use <- 1

gt_path <- file.path(results_dir, paste0(iteration_to_use, gt_sample_prefix, ".txt"))
syn_path <- file.path(results_dir, paste0(iteration_to_use, syn_sample_prefix, ".txt"))

# Check if the files exist
if (!file.exists(gt_path) || !file.exists(syn_path)) {
  stop("Data files not found. Please run latentModel.R first to generate the data.")
}

# Load the data
gt_sample <- read.delim(gt_path)
syn_sample <- read.delim(syn_path)

cat("\n--- Data Summary Comparison ---\n\n")

cat("Ground Truth Data Summary:\n")
print(dfSummary(gt_sample), method = "render")

cat("\nSynthetic Data Summary:\n")
print(dfSummary(syn_sample), method = "render")


# -----------------------------------------------------------------------------
# Train a Predictive Model
# -----------------------------------------------------------------------------

cat("\n--- Training a Predictive Model on Synthetic Data ---\n\n")

# We will train a logistic regression model to predict 'strokeha'

# The 'train' function from caret needs the outcome to be a factor with valid level names
# Let's make sure the levels are valid R variable names
levels(syn_sample$strokeha) <- make.names(levels(syn_sample$strokeha))
levels(gt_sample$strokeha) <- make.names(levels(gt_sample$strokeha))


# Define the model formula
# Using a subset of variables for demonstration purposes
formula <- strokeha ~ age + bmi + gender + choleratio + sbp

# Train the logistic regression model on the synthetic data
set.seed(123) # for reproducibility
model <- train(
  formula,
  data = syn_sample,
  method = "glm",
  family = "binomial",
  trControl = trainControl(method = "none") # No resampling for this demo
)

cat("Model trained on synthetic data:\n")
print(summary(model))


# -----------------------------------------------------------------------------
# Evaluate the Model on Ground Truth Data
# -----------------------------------------------------------------------------

cat("\n--- Evaluating the Model on Ground Truth Data ---\n\n")

# Make predictions on the ground truth data
predictions <- predict(model, newdata = gt_sample)

# Create a confusion matrix
# Note: The levels of the prediction and the actual data must match.
# The 'strokeha' variable in gt_sample should have the same levels as in syn_sample.
confusion_matrix <- confusionMatrix(predictions, gt_sample$strokeha)

cat("Confusion Matrix and Statistics:\n")
print(confusion_matrix)

cat("\n--- Demonstration Complete ---\n")
