# This script generates tables and figures for comparing the ground truth (GT)
# and synthetic (SYN) data. It performs several experiments as described in the paper.

# Load libraries
library(RevoScaleR)
library(summarytools)
library(LaplacesDemon)
library(kernlab)
library(dplyr)
library(SuperLearner)
library(precrec)
library(lmtest) # For grangertest

# Load configuration
source("scripts/config.R")

# -----------------------------------------------------------------------------
# Helper Functions
# -----------------------------------------------------------------------------

# Function to load a pair of GT and SYN sample files
load_samples <- function(iteration) {
  gt_path <- file.path(results_dir, paste0(iteration, gt_sample_prefix, ".txt"))
  syn_path <- file.path(results_dir, paste0(iteration, syn_sample_prefix, ".txt"))

  list(
    gt = read.delim(gt_path),
    syn = read.delim(syn_path)
  )
}

# Function to plot density of continuous variables
plot_density_comparison <- function(gt_data, syn_data, var_name) {
  plot(density(na.omit(gt_data[[var_name]])), main = paste("Density Plot for", var_name), xlab = "Value", col = "blue")
  lines(density(na.omit(syn_data[[var_name]])), col = "red")
  legend("topright", legend = c("Ground Truth", "Synthetic"), col = c("blue", "red"), lty = 1)
}

# -----------------------------------------------------------------------------
# Experiment I & II: Distribution Comparison
# -----------------------------------------------------------------------------

run_distribution_comparison <- function(iteration, with_missing = TRUE) {
  samples <- load_samples(iteration)
  gt_sample <- samples$gt
  syn_sample <- samples$syn

  if (!with_missing) {
    gt_sample <- na.omit(gt_sample)
    syn_sample <- na.omit(syn_sample)
  }

  # Balance sample sizes
  min_size <- min(nrow(gt_sample), nrow(syn_sample))
  gt_sample <- sample_n(gt_sample, min_size)
  syn_sample <- sample_n(syn_sample, min_size)

  cat("\n--- Summary for Iteration", iteration, "---\n")
  cat("\nGround Truth Summary:\n")
  print(dfSummary(gt_sample), method = "render")
  cat("\nSynthetic Data Summary:\n")
  print(dfSummary(syn_sample), method = "render")

  # Plot density comparisons for continuous variables
  continuous_vars <- c("age", "bmi", "choleratio")
  for (var in continuous_vars) {
    plot_density_comparison(gt_sample, syn_sample, var)
  }
}

cat("--- Running Experiment I (without missing data) ---\n")
# run_distribution_comparison(12, with_missing = FALSE) # Assuming iteration 12 is for this

cat("\n--- Running Experiment II (with missing data) ---\n")
# run_distribution_comparison(11, with_missing = TRUE) # Assuming iteration 11 is for this


# -----------------------------------------------------------------------------
# Experiment III: Chi-square Test for Categorical Variables
# -----------------------------------------------------------------------------

run_chi_square_tests <- function(iteration) {
  samples <- load_samples(iteration)
  gt_sample <- samples$gt
  syn_sample <- samples$syn

  categorical_vars <- names(gt_sample)[sapply(gt_sample, is.factor)]

  results <- data.frame(variable = character(), p_value = numeric(), stringsAsFactors = FALSE)

  for (var in categorical_vars) {
    test <- chisq.test(gt_sample[[var]], syn_sample[[var]])
    results <- rbind(results, data.frame(variable = var, p_value = test$p.value))
  }

  cat("\n--- Chi-square Test Results for Iteration", iteration, "---\n")
  print(results)
}

# run_chi_square_tests(11) # Assuming iteration 11 is used for this test


# -----------------------------------------------------------------------------
# Experiment IV: KS Test for Continuous Variables
# -----------------------------------------------------------------------------

run_ks_tests <- function(iteration) {
  samples <- load_samples(iteration)
  gt_sample <- na.omit(samples$gt)
  syn_sample <- na.omit(samples$syn)

  continuous_vars <- c("age", "bmi", "choleratio", "sbp", "sbps")

  results <- data.frame(variable = character(), p_value = numeric(), stringsAsFactors = FALSE)

  for (var in continuous_vars) {
    test <- ks.test(gt_sample[[var]], syn_sample[[var]])
    results <- rbind(results, data.frame(variable = var, p_value = test$p.value))
  }

  cat("\n--- KS Test Results for Iteration", iteration, "---\n")
  print(results)
}

# run_ks_tests(12) # Assuming iteration 12 is used for this test

# --- KS test for KLD values ---
# This part assumes a KLDS.txt file is generated elsewhere.
# If it's generated by this script, the logic should be integrated.
# klds_data <- read.csv(klds_file)
# ks.test(klds_data$age_sy, klds_data$age_gt)
# ... and so on for other variables


# -----------------------------------------------------------------------------
# Experiment V: Kullback-Leibler Divergence (KLD) Comparison
# -----------------------------------------------------------------------------

calculate_kld <- function(gt_values, syn_values) {
  den_gt <- density(na.omit(gt_values))
  den_syn <- density(na.omit(syn_values))
  KLD(den_gt$y, den_syn$y)$sum.KLD.px.py
}

run_kld_analysis <- function(iterations, population_data) {
  kld_results_gt <- list()
  kld_results_syn <- list()
  continuous_vars <- c("age", "bmi", "choleratio", "sbp", "sbps")

  for (i in iterations) {
    samples <- load_samples(i)

    # KLD between synthetic and population
    kld_syn_iter <- sapply(continuous_vars, function(var) {
      calculate_kld(population_data[[var]], samples$syn[[var]])
    })
    kld_results_syn[[i]] <- kld_syn_iter^2

    # KLD between ground truth sample and population
    kld_gt_iter <- sapply(continuous_vars, function(var) {
      calculate_kld(population_data[[var]], samples$gt[[var]])
    })
    kld_results_gt[[i]] <- kld_gt_iter^2
  }

  kld_syn_df <- as.data.frame(do.call(rbind, kld_results_syn))
  kld_gt_df <- as.data.frame(do.call(rbind, kld_results_gt))

  cat("\n--- KLD Analysis Results ---\n")
  cat("\nAverage KLD for Synthetic Data:\n")
  print(colMeans(kld_syn_df))
  cat("\nAverage KLD for Ground Truth Samples:\n")
  print(colMeans(kld_gt_df))

  return(list(syn = kld_syn_df, gt = kld_gt_df))
}

# population <- read.delim(ground_truth_file)
# kld_results <- run_kld_analysis(1:10, population)


# -----------------------------------------------------------------------------
# Experiment VI: Maximum Mean Discrepancy (MMD)
# -----------------------------------------------------------------------------

run_mmd_analysis <- function(iterations, population_data, sample_size = 1000) {
  for (m in iterations) {
    gt_sample <- sample_n(population_data, sample_size)
    gt_sample[is.na(gt_sample)] <- -1

    samples <- load_samples(m)
    syn_sample <- sample_n(samples$syn, sample_size)
    syn_sample[is.na(syn_sample)] <- -1

    output_file <- file.path(results_dir, paste0("mmd_results_iter_", m, ".txt"))

    for (k in 2:4) { # Combinations of 2, 3, and 4 variables
      var_combinations <- combn(names(gt_sample), k, simplify = FALSE)

      for (i in var_combinations) {
        x <- data.matrix(gt_sample[, i, drop = FALSE])
        y <- data.matrix(syn_sample[, i, drop = FALSE])

        mmdo <- kmmd(x, y)

        joint_vars <- paste(i, collapse = ":")
        cat(paste(joint_vars, mmdo@H0, sep = ","), "\n", file = output_file, append = TRUE)
      }
    }
  }
}

# run_mmd_analysis(1:10, population)


# -----------------------------------------------------------------------------
# Experiment VII: PRC and ROC Analysis
# -----------------------------------------------------------------------------

run_prc_roc_analysis <- function(iterations, sample_size = 100000, train_ratio = 0.8) {
  results <- list()

  for (m in iterations) {
    samples <- load_samples(m)

    # Prepare GT data
    gt_data <- as.data.frame(lapply(sample_n(samples$gt, sample_size), as.numeric))
    gt_data[is.na(gt_data)] <- -1

    # Prepare SYN data
    syn_data <- as.data.frame(lapply(sample_n(samples$syn, sample_size), as.numeric))
    syn_data[is.na(syn_data)] <- -1

    # Split data
    train_index_gt <- 1:(nrow(gt_data) * train_ratio)
    train_index_syn <- 1:(nrow(syn_data) * train_ratio)

    gt_train_y <- gt_data[train_index_gt, ]$strokeha
    gt_train_x <- subset(gt_data[train_index_gt, ], select = -strokeha)

    syn_train_y <- syn_data[train_index_syn, ]$strokeha
    syn_train_x <- subset(syn_data[train_index_syn, ], select = -strokeha)

    gt_test_y <- gt_data[-train_index_gt, ]$strokeha
    gt_test_x <- subset(gt_data[-train_index_gt, ], select = -strokeha)

    # Train model on synthetic data
    fit <- SuperLearner(
      Y = syn_train_y,
      X = syn_train_x,
      family = "gaussian",
      cvControl = list(V = 10L, stratifyCV = TRUE),
      SL.library = c("SL.bayesglm")
    )

    # Predict on GT test data
    gt_pred <- predict(fit, newdata = gt_test_x)

    # For PRC/ROC, need predictions on synthetic test data as well
    syn_test_y <- syn_data[-train_index_syn, ]$strokeha
    syn_test_x <- subset(syn_data[-train_index_syn, ], select = -strokeha)
    syn_pred <- predict(fit, newdata = syn_test_x)

    # Create evaluation object
    scores <- join_scores(as.numeric(syn_pred$pred), as.numeric(gt_pred$pred))
    labels <- join_labels(syn_test_y, gt_test_y)
    msmdat <- mmdata(scores, labels, modnames = c("SYN", "GT"), dsids = c(1, 2))

    results[[m]] <- msmdat
  }

  # Evaluate and plot
  datapoints <- evalmod(results[[1]]) # Evaluate on the first iteration's results
  plot(datapoints)

  # Granger causality test for PRC and ROC curves
  rocs <- attr(datapoints, "grp_avg")[[1]]
  prcs <- attr(datapoints, "grp_avg")[[2]]

  roc_syn <- rocs[[1]]$y_avg
  roc_gt <- rocs[[2]]$y_avg
  prc_syn <- prcs[[1]]$y_avg
  prc_gt <- prcs[[2]]$y_avg

  roc_granger <- grangertest(roc_gt ~ roc_syn, order = 1)
  prc_granger <- grangertest(prc_gt ~ prc_syn, order = 1)

  cat("\n--- PRC and ROC Analysis Results ---\n")
  print(roc_granger)
  print(prc_granger)

  # AUC values
  aucs <- as.data.frame(attr(datapoints, 'aucs'))
  cat("\nAUC values:\n")
  print(aucs)
}

# run_prc_roc_analysis(1:10)
